### ISSUE TITLE
подключить стиралку в ванной

### ISSUE THREAD

**Issue by Paragonid** [Paragonid/living-flat#3]

**Comment by Paragonid** [comment]
@LogicDaemon ты точно спланировал со стиралкой в ванной? там места будет притык, если вообще хватит

**Comment by LogicDaemon** [comment]
да, я замерял и план рисовал.
![default](https://user-images.githubusercontent.com/7845494/36073112-3bb42cae-0f3c-11e8-96e3-206791d76183.png)

(правда, в плане стиралка узкая, а я купил обычную, но всё равно видно, что влезает)
